src/app/components/home.tsx

refactor: codecard positioning

---

src/app/Docs/page.jsx
src/app/components/docsbar.tsx
src/app/components/footer.tsx
src/app/components/sidebar.tsx

footer has padding 
it making footer taking extra space
added docs page

feat: <Docs> added and footer changes

---

src/app/components/showcase.tsx
src/app/components/sidebar.tsx

Updated showcase component styling
Fixed sidebar navigation issue

feat: <showcase> styling and <sidebar> issue solved

---

src/app/components/docsbar.tsx
src/app/components/showcase.tsx
src/app/components/testimonials.tsx

docsbar improved for sm
showcase particles reduced
testimonials name style improved

refactor: Modifiedfiles

---

src/app/contributions/index.html

feat: contributions added

---

src/app/contributions/divrevellingeffect.css
src/app/contributions/divrevellingeffect.html

Fix : #13
divrevellingeffect added

feat: divrevellingeffect added

---

src/app/TScontributions/TSdivreveal.tsx

refactor: <TSdivreveal.tsx> changes

---

src/app/contributions/solarsystem.css
src/app/contributions/solarsystem.html
src/app/contributions/solarsystem.js

components for solar system added

feat: solarsystemadded

---

src/app/page.tsx

fix: removed unused declaration

---

src/app/contributions/solarsystem.css
src/app/contributions/solarsystem.html
src/app/contributions/solarsystem.js

refactor: ssolarsystemadded

---

src/app/page.tsx

feat: Update page.tsx

---

src/app/TScontributions/TSkeyboard.tsx

feat: Update TSkeyboard.tsx

---

CONTRIBUTING.md
README.md
next.config.js
src/app/TScontributions/TSkeyboard.tsx
src/app/components/showcase.tsx
src/app/components/sidebar.tsx
src/app/sidebarmenu/Smoothkeyboard.tsx

feat: prettier formatting

---

src/app/page.tsx

Removed unused imports
fixes: #54 

feat: Refactor page.tsx

---

README.md

docs: Update README with contributors section improvements

---

src/app/components/testimonials.tsx

feat: <Testimonials> bug fixed

---

src/app/sidebarmenu/InstallNextJS.tsx

feat: highlighted text in InstallNextjs

---

src/app/sidebarmenu/InstallTailwindCss.tsx

feat: <updated InstallTailwindCss.tsx>

---

src/app/TScontributions/TSlamphome.tsx

feat: <TSlamphome.tsx> added

---

src/app/TScontributions/TSlamphome.tsx

HomeStyle component, a visually interactive and animated UI built with Next.js, Framer Motion, and Tailwind CSS.
refactor: #85 
https://github.com/user-attachments/assets/daff585a-2a9f-46bf-9788-d0023ddffd90

feat: refactor styles in  <TSlamphome.tsx>

---

src/app/contributions/squidloader.css
src/app/contributions/squidloader.html

feat: added squidloader

---

next-sitemap.config.js
public/sitemap-0.xml
public/sitemap.xml

Describe problems, if any, clearly and concisely.
Summarize the impact to the system.
Please also include relevant motivation and context.
Please include a summary of the technical solution and how it solves the problem.

feat: sitemap updated

---

src/components/SearchModal.tsx

feat: error fixed

---

package.json
pnpm-lock.yaml

feat: dep added

---

src/types/styled-jsx.d.ts

feat: resolving typecheck error

---

package.json

feat: jest error resolved

---

src/components/Navbar.tsx

refactor: <Navbar.tsx /> updated

---

src/app/docs/layout.tsx

refactor: docslayout making responsive

---

src/components/Navbar.tsx

refactor: routes of component

---

src/components/HeroSection.tsx

refactor: routng issue fixed

---

src/components/Sidebar.tsx

refactor: animation anchortageffect

---

src/components/HeroSection.tsx

refactor: <herosection.tsx /> for system

---

LICENSE

Chore add MIT LICENSE

---

src/components/HeroSection.tsx
src/components/MdxRenderer.tsx
src/components/Navbar.tsx
src/components/OnThisPage.tsx
src/components/SearchModal.tsx

feat: cleanup

---

jest.setup.js
next-sitemap.config.js
next.config.js
src/app/ClientBody.tsx
src/app/debug/page.tsx
src/app/docs/layout.tsx
src/components/Sidebar.tsx
src/lib/mdx.ts
src/types/mdx.d.ts

feat: optimization and cleanup

---

src/app/layout.tsx

Refactor <layout.tsx />

---

package.json
pnpm-lock.yaml
src/components/Component-preview.tsx

feat: componentpreview a system building

---

public/favicon/site.webmanifest
src/app/layout.tsx

refactor: manifest added

---

src/app/docs/[[...slug]]/page.tsx
src/app/registry/registry.tsx
src/components/Component-preview.tsx
src/components/demos/accordion-demo.tsx
src/components/mdx-components.tsx
src/content/docs/components/accordion.mdx

feat: building component-preview system

---

src/app/docs/layout.tsx

refactor: update <docslayout.tsx />

---

CONTRIBUTING.md
LICENSE.md
README.md
src/actions/getComponentSourceAction.ts
src/app/registry/registry.tsx
src/components/Component-preview.tsx
src/content/docs/components/accordion.mdx
src/utils/componentSource.ts

feat: system process

---

package.json
pnpm-lock.yaml
src/components/code-block-wrapper.tsx
src/components/component-source.tsx
src/components/ui/collapsible.tsx

feat: system buildig continued

---

src/components/ui/accordion.tsx

refactor: updated <accordion.tsx />

---

next.config.js
package.json
pnpm-lock.yaml
src/types/declarations.d.ts
src/utils/componentSource.ts

refactor: updated <componentsource.ts />

---

src/app/docs/[[...slug]]/page.tsx
src/components/OnThisPage.tsx

fix: #160 
properly configured the onthispage.tsx and slug/page.tsx to scroll on clicking headings

refactor: added scrolling on links

---

src/content/docs/introduction.mdx

refactor: updated <introduction.mdx />

---

src/components/Component-preview.tsx

Added the button into seperate div and fixed alignment issue
Fix: #164 

refactor: 🎉 Update <Component-preview.tsx />

---

src/components/Component-preview.tsx

fix: #166 
moved button outside of relative div

refactor: updated <component-preview.tsx />

---

src/content/docs/components/accordion.mdx

refactor: removed unused imports

---

package.json
pnpm-lock.yaml
src/actions/getParentSourceAction.ts
src/app/docs/layout.tsx
src/components/code-block-wrapper.tsx
src/components/component-source.tsx
src/components/mdx-components.tsx
src/content/docs/components/accordion.mdx
src/types/react-syntax-highlighter.d.ts
src/utils/parentSource.ts

feat: added new Actions,utils and component

---

src/components/Component-preview.tsx
src/components/component-source.tsx

refactor: sourcecode highlighted

---

src/components/mdx-components.tsx
src/components/pkgoptions.tsx
src/content/docs/components/accordion.mdx

feat: added options

---

src/app/docs/[[...slug]]/page.tsx
src/content/docs/components/accordion.mdx
src/content/docs/installation.mdx
src/content/docs/introduction.mdx

refactor: seo fixes

---

public/sitemap-0.xml
src/app/docs/[[...slug]]/page.tsx
src/app/layout.tsx

refactor: improved scalability

---

package.json
pnpm-lock.yaml
src/app/registry/demos.ts
src/app/registry/parents.ts
src/app/registry/registry.tsx
src/components/demos/alertdialog-demo.tsx
src/components/ui/alert-dialog.tsx
src/components/ui/button.tsx
src/constants/navItems.ts
src/content/docs/components/alert-dialog.mdx
src/utils/componentSource.ts
src/utils/parentSource.ts

feat: error handling

---

src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/Sidebar.tsx
src/components/demos/spotlightcard-demo.tsx
src/components/ui/spotlightcard.tsx
src/constants/navItems.ts
src/content/docs/components/spotlightcard.mdx

feat: <spotlightcard /> added

---

package.json
pnpm-lock.yaml
src/app/docs/[[...slug]]/page.tsx
src/app/globals.css
src/components/CodeBlock.tsx
src/components/demos/spotlightcard-demo.tsx
src/content/docs/components/accordion.mdx
src/content/docs/components/alert-dialog.mdx
src/content/docs/components/spotlightcard.mdx

refactor: enhanced and removed bugs

---

public/favicon/site.webmanifest
src/app/registry/registry.tsx
tailwind.config.ts
tsconfig.json

refactor: improved structure

---

src/app/docs/[[...slug]]/page.tsx

refactor: metadata generation improved

---

src/app/sitemap.xml/route.ts

refactor: corrected url in sitemap

---

src/app/layout.tsx

refactor: improved seo

---

src/app/layout.tsx

refactor: verification

---

package.json
pnpm-lock.yaml
src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/aspectratio-demo.tsx
src/components/ui/aspect-ratio.tsx
src/constants/navItems.ts
src/content/docs/components/aspect-ratio.mdx

feat: <aspectratio /> added

---

package.json
pnpm-lock.yaml
src/app/layout.tsx
src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/avatar-demo.tsx
src/components/ui/avatar.tsx
src/content/docs/components/avatar.mdx

feat: <avatar /> added

---

src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/button-demo.tsx
src/content/docs/components/button.mdx

feat: <button /> added in registry

---

src/components/Footer.tsx

refactor: links updated

---

src/components/depsoptions.tsx
src/components/pkgoptions.tsx
src/components/ui/tabs.tsx
src/content/docs/components/accordion.mdx

refactor: updated with context

---

src/app/layout.tsx

refactor: indexed

---

src/content/docs/components/card.mdx

refactor: title should be capital

---

src/components/OnThisPage.tsx
src/components/Sidebar.tsx
src/constants/navItems.ts
src/content/docs/installation/cli.mdx
src/content/docs/installation/manual.mdx

feat: improvised for manual

---

vercel.json

feat: vercel.json added

---

src/components/CodeBlock.tsx
src/content/docs/installation/cli.mdx

refactor: cli and styles  updated

---

src/app/globals.css

refactor: scrollbar styled

---

tailwind.config.ts

BACKTICKS ISSUE SOLVED
fix: #235 

refactor: backticks error solved

---

package.json
pnpm-lock.yaml
src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/profilecard-demo.tsx
src/components/ui/profilecard.tsx
src/constants/navItems.ts
src/content/docs/components/profilecard.mdx

feat: <profilecard /> added to registry

---

src/components/SearchModal.tsx

refactor: updated <searchmodal />

---

src/app/docs/[[...slug]]/page.tsx
src/components/ui/Navigator.tsx

feat: navigator added

---

src/components/ui/Navigator.tsx

refactor: updated navigator for minor issues

---

src/components/demos/eyeglasses-demo.tsx
src/components/ui/eyeglasses.tsx

feat: <eyeglasses /> added

---

src/components/demos/profilecard-demo.tsx
src/components/ui/profilecard.tsx

refactor: <profilecard /> accept skills as urls

---

src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/animatedshowcase-demo.tsx
src/components/demos/eyeglasses-demo.tsx
src/components/ui/animated-showcase.tsx
src/constants/navItems.ts
src/content/docs/components/animated-showcase.mdx

feat: <animatedshowcase /> added to registry

---

src/components/ui/lamphome.tsx

feat: <lamphome /> added

---

src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/lamphome-demo.tsx
src/components/ui/lamphome.tsx
src/constants/navItems.ts
src/content/docs/components/lamphome.mdx

feat: <lamphome /> added to registry

---

src/components/Component-preview.tsx
src/components/ui/lamphome.tsx

refactor: revamped and bugs fixes

---

src/components/ui/light-trail.tsx

feat: light-trail addition

---

src/app/docs/[[...slug]]/page.tsx

refactor: extra padding removed

---

src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/lighttrail-demo.tsx
src/components/ui/light-trail.tsx
src/constants/navItems.ts
src/content/docs/components/light-trail.mdx

feat: <lighttrail />  added to registry

---

src/constants/navItems.ts

fix route in Navitems
fix: #265 

Updated navItems.ts

---

src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/glowingbordercard-demo.tsx
src/components/ui/glowingbordercard.tsx
src/constants/navItems.ts
src/content/docs/components/glowingbordercard.mdx

feat: <glowingbordercard /> added in registry

---

src/components/SearchModal.tsx

Refactor: Updated SearchModal.tsx

---

src/constants/navItems.ts
src/content/docs/installation.mdx
src/content/docs/installation/install-tailwindcss.mdx
src/content/docs/introduction.mdx

feat: installation guide configured properly

---

src/app/docs/layout.tsx

refactor: ui enhanced

---

src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/animatedbutton-demo.tsx
src/components/demos/card-demo.tsx
src/components/ui/animated-button.tsx
src/constants/navItems.ts
src/content/docs/components/animated-button.mdx

feat: <animatedbutton /> added

---

src/app/globals.css
src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/lustretext-demo.tsx
src/components/ui/lustretext.tsx
src/constants/navItems.ts
src/content/docs/components/lustretext.mdx

feat: <lustretext /> added in registry

---

src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/magicdock-demo.tsx
src/components/ui/magicdock.tsx
src/constants/navItems.ts
src/content/docs/components/magicdock.mdx

feat: <magicdock /> added in registry

---

src/components/ui/magicdock.tsx

refactor: <magicdock /> optimized

---

src/components/ui/magicdock.tsx

refactor: <magicdock /> updated

---

src/app/registry/registry.tsx

refactor: issue fixed

---

src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/themeswitch-demo.tsx
src/components/demos/thsinglecentredthree.tsx
src/components/demos/thsinglecentredtwo.tsx
src/components/demos/thswitchhideinactive.tsx
src/components/demos/thswitchstdall.tsx
src/components/demos/thswitchthreenext.tsx
src/components/demos/thswitchtwonext.tsx
src/components/ui/theme-switch.tsx
src/constants/navItems.ts
src/content/docs/components/theme-switch.mdx

feat: <themeswitch /> added in registry

---

src/components/demos/carouselimage-demo.tsx

refactor: loading issue fixed

---

package.json
pnpm-lock.yaml
src/components/demos/toaster-demo.tsx
src/components/ui/toaster.tsx
tailwind.config.ts

feat: <toaster /> added

---

src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/seperatorpro-demo.tsx
src/components/demos/seperatorprodotted.tsx
src/components/demos/seperatorprowavy.tsx
src/components/ui/seperatorpro.tsx
src/constants/navItems.ts
src/content/docs/components/seperatorpro.mdx

feat: <seperatorpro /> added in registry

---

package.json
pnpm-lock.yaml
src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/followcursor-demo.tsx
src/components/ui/followcursor.tsx
src/constants/navItems.ts
src/content/docs/components/followcursor.mdx

feat: <followcursor /> added in registry

---

package.json
pnpm-lock.yaml
src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/pagination-demo.tsx
src/components/ui/pagination.tsx
src/constants/navItems.ts
src/content/docs/components/pagination.mdx

feat: <pagination /> added in registry

---

src/app/globals.css
src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/radialflow-demo.tsx
src/components/ui/radialflow.tsx
src/constants/navItems.ts
src/content/docs/components/radialflow.mdx

feat: <radialflow /> added in registry

---

src/components/OnThisPage.tsx
src/components/ui/scroll-area.tsx

refactor: <onthispage /> updated

---

src/components/HeroSection.tsx

refactor: link updated

---

src/components/HeroSection.tsx

refactor: <herosection /> updated

---

src/components/ui/globe.tsx
src/content/docs/components/globe.mdx

refactor: <globe /> context lost fixed

---

src/app/docs/layout.tsx

refactor: <layout /> updated

---

CONTRIBUTING.md

refactor: <contributing.md /> updated

---

vercel.json

chore: remove unused vercel.json config file

---

src/constants/navItems.ts
src/content/docs/components/animated-testimonials.mdx

refactor: removed unused code

---

src/components/Testimonials.tsx
src/components/TestimonialsSection.tsx
src/components/ui/animated-testimonials.tsx

refactor: <testimonialsection /> updated

---

package.json
pnpm-lock.yaml
src/components/HeroSection.tsx

refactor: <herosection />

---

src/components/Component-preview.tsx

refactor: <componentpreview /> updated

---

src/components/Navbar.tsx
src/components/navsheet.tsx

feat: <navsheet /> added

---

package.json
pnpm-lock.yaml
src/components/ui/drawer.tsx

feat: <drawer /> added

---

src/constants/navItems.ts

refactor: <Navitems /> updated

---

src/constants/navItems.ts
src/content/docs/components/cursorimagetrail.mdx
src/content/docs/components/followcursor.mdx

refactor: <componentpreview  />updated in mdx files

---

package.json
pnpm-lock.yaml
src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/statscount-demo.tsx
src/components/ui/statscount.tsx
src/constants/navItems.ts
src/content/docs/components/statscount.mdx

feat: <statscount5 /> added in registry

---

src/components/ui/input-otp.tsx

refactor: <input-otp /> removed unused code

---

src/components/demos/spotlightcard-demo.tsx
src/components/ui/spotlightcard.tsx
src/content/docs/components/spotlightcard.mdx

refactor: <spotlightcard /> updated

---

src/components/demos/glowingbordercard-demo.tsx
src/components/ui/glowingbordercard.tsx
src/content/docs/components/glowingbordercard.mdx
src/content/docs/components/spotlightcard.mdx

refactor: <components,demos & mdx />

---

src/app/globals.css
src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/Component-preview.tsx
src/components/demos/whitestripes-demo.tsx
src/components/ui/whitestripes.tsx
src/constants/navItems.ts
src/content/docs/components/whitestripes.mdx

feat: <whitestripes /> added to registry

---

src/app/page.tsx
src/components/ui/kinetic-testimonial.tsx

feat: <kinetictestimonials /> added

---

src/app/api/og/route.tsx

refactor: fix rendering issue

---

.github/workflows/release-please.yml

refactor: removed comments

---

src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/backgroundpaths-demo.tsx
src/components/ui/background-paths.tsx
src/constants/navItems.ts
src/content/docs/components/background-paths.mdx

feat: <background-paths /> added to registry

---

src/components/Navbar.tsx
src/components/navsheet.tsx

refactor: <navbar /> & <navsheet />

---

src/app/docs/layout.tsx
src/components/docsfooter.tsx

feat: <docsfooter /> added

---

src/app/docs/layout.tsx
src/components/mdx-components.tsx
src/components/propstable.tsx
src/content/docs/components/typeanimation.mdx

feat: <propstable /> added

---

src/app/not-found.tsx

refactor: dvh on <not-found />

---

src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/notfound-demo.tsx
src/components/ui/not-found.tsx
src/constants/navItems.ts
src/content/docs/components/not-found.mdx

feat: <404 not-found /> added to registry

---

src/components/githubstarspotlightcard.tsx

refactor: used next/link

---

src/components/Footer.tsx

refactor: <footer /> updated

---

src/components/SearchModal.tsx

refactor: <searchmodal /> updated

---

src/app/templates/page.tsx

refactor: <templates /> updated

---

src/constants/project-list.ts

refactor: <project-lists /> updated

---

src/components/ui/kinetic-testimonial.tsx

refactor: <kinetic-testimonials /> updated

---

src/app/page.tsx
src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/kinetictestimonials-demo.tsx
src/components/testimonial.tsx
src/components/ui/kinetic-testimonials.tsx
src/constants/navItems.ts
src/content/docs/components/kinetic-testimonials.mdx
tailwind.config.ts

feat: <kinetic-testimonials /> added

---

src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/statscarousel-demo.tsx
src/components/ui/statscarousel.tsx
src/constants/navItems.ts
src/content/docs/components/statscarousel.mdx

feat: <statscarousel /> added to registry

---

src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/animatedtextgenerate-demo.tsx
src/components/ui/animated-textgenerate.tsx
src/constants/navItems.ts
src/content/docs/components/animated-textgenerate.mdx

feat: <animated-textgenerate /> addded to registry

---

src/components/component-source.tsx

refactor: <compone4nt-source /> updated

---

public/registry/accordion.json
registry.json

feat: <registry.json /> added

---

src/components/pkgoptions.tsx

refactor: <pkgoptions /> updated

---

src/content/docs/components/animated-button.mdx

This PR corrects the usage of the `PkgOptions` component in the `animated-button.mdx` documentation page.

refactor: fixed typos in pkgoptions

---

src/content/docs/installation/cli.mdx
src/content/docs/introduction.mdx

added  automation to install and scaffold components
fix: #544 

refactor: updated <cli />

---

src/content/docs/components/lustretext.mdx

refactor: <lustretext.mdx /> updated

---

src/constants/navItems.ts
src/content/docs/components/accordion.mdx
src/content/docs/components/animated-testimonials.mdx
src/content/docs/components/badge.mdx
src/content/docs/components/codeblock.mdx
src/content/docs/components/followcursor.mdx
src/content/docs/components/kinetic-testimonials.mdx
src/content/docs/components/lamphome.mdx
src/content/docs/components/light-trail.mdx
src/content/docs/components/lustretext.mdx
src/content/docs/components/spotlightcard.mdx
src/content/docs/components/toast.mdx

chore(cli): cleanup mdx and expose all components to CLI

---

src/components/ui/navbarflow.tsx

added a navbarflow component in ui 
experimental

feat: <navbarflow /> added in ui

---

src/components/FeaturesSection.tsx

refactor: updated FeaturesSection 

---

public/registry/expandable-dock.json
registry.json
src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/expandabledock-demo.tsx
src/components/ui/expandable-dock.tsx
src/constants/navItems.ts
src/content/docs/components/expandable-dock.mdx

**Summary:**
This PR introduces the `<expandable-dock />` component
* Registry updates (`registry.json`, `demos.ts`, `parents.ts`, `navItems.ts`)
* New demo component and related UI files (`expandabledock-demo.tsx`, `expandable-dock.tsx`)
* Documentation updates (`expandable-dock.mdx`) for component usage
The component is now fully integrated and documented.
feat: #578

feat: <expandable-dock /> added to registry & docs

---

src/content/docs/introduction.mdx

feat: producthunt-badge added in introduction

---

src/components/Component-preview.tsx
src/content/docs/installation.mdx
src/content/docs/installation/install-tailwindcss.mdx
src/content/docs/installation/manual.mdx

The installation documentation had inconsistencies, unclear Tailwind CSS v3 steps, and formatting differences.  
`Component-preview.tsx` also had less maintainable structure, making it harder to modify in the future.
- Improves onboarding experience for new ScrollX UI users.
- Ensures Tailwind CSS v3 installation steps are clear and correct.
- Enhances maintainability of the `Component-preview` component.
This update aligns all installation-related documentation with the latest standards and improves code clarity in `Component-preview.tsx`, making future updates easier and safer.
- **Documentation:**
- Updated `src/content/docs/installation.mdx` for improved clarity.
- Revised `src/content/docs/installation/install-tailwindcss.mdx` 
- Cleaned up `src/content/docs/installation/manual.mdx` …

refactor: update documentation and component preview

---

public/registry/flowing-logos.json
registry.json
src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/flowinglogos-demo.tsx
src/components/ui/flowing-logos.tsx
src/constants/navItems.ts
src/content/docs/components/flowing-logos.mdx

This PR introduces the new **FlowingLogos** component to the library.
Displaying multiple brand or partner logos with modern smooth scrolling effects typically requires custom CSS animations or third-party libraries. Existing solutions like `<marquee>` or sliders are outdated, limited, or heavy for such a simple use case.
This component allows developers to easily showcase logos in a **premium, polished way** with minimal setup. It provides smooth animations, pause-on-hover interactions, and customizable options, improving the developer experience and end-user UI quality.
- Added `FlowingLogos` component with reusable `FlowingLogo` and `LogoCard` subcomponents.  
- Features include:
- Horizontal scrolling
- Direction toggle (`reverse`)
- Adjustable duration, repeat count, and masking
- …

feat: <flowing-logos /> added to registry & docs

---

src/app/docs/[[...slug]]/page.tsx
src/components/Navigator.tsx

fixed buttons alignment in navigator 
closes: #639

refactor: <navigator /> moved to components from ui

---

src/components/ComponentShowcase.tsx

Update the `ComponentShowcase` section to refactor and include new demos/components.  
New additions:  
- `HoldToConfirmDemo`  
- `ProfileCardDemo`  
- `GravityDemo`  
- `MotionCardsDemo`  
- `RadialSocialsDemo`  
- Interactive `Transition` section with replay/refresh buttons  
Updated Tabs layout to have **Interactive**, **Animated**, and **Creative** categories.  
Refactored `ShowcasePanel` styling for consistent height, rounded corners, and overflow handling.
feat: #672

refactor: <componentshowcase /> showcases cool components

---

package.json
pnpm-lock.yaml
public/registry/popover.json
registry.json
src/app/registry/demos.ts
src/app/registry/parents.ts
src/components/demos/popover-demo.tsx
src/components/ui/popover.tsx
src/constants/navItems.ts
src/content/docs/components/popover.mdx

This PR introduces a new `Popover` component to the library to display rich content in an animated portal. The component includes:
- `Popover` – the root wrapper.
- `PopoverTrigger` – triggers the popover.
- `PopoverContent` – content container with animations.
- `PopoverAnchor` – optional positioning anchor.
Animations are powered by `framer-motion` and allow smooth entry and exit. The component uses `Radix UI Popover` internally to handle accessibility and portal behavior.
- **Added**
- `src/components/ui/popover.tsx`
- `src/components/demos/popover-demo.tsx`
- `public/registry/popover.json`
- `src/content/docs/components/popover.mdx`
- **Modified**
- `package.json`
- `pnpm-lock.yaml`
- `registry.json`
- `src/app/registry/demos.ts`
- `src/app/registry/parents.ts`
- …

feat: <popover /> added to registry & docs
